apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /var/nfs/general
    server: 172.31.24.197
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: drupal-nfs-pv
